services:
  - type: web
    name: my-backend-service
    env: node
    plan: free
    buildCommand: "cd backend && npm install && npm run build"
    startCommand: "cd backend && node dist/server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false