name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set GCP Project
        run: |
          gcloud config set project ${{ secrets.GCLOUD_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.GCLOUD_REGION }}

      - name: Enable Google Cloud APIs
        run: |
          gcloud services enable run.googleapis.com
          gcloud services enable cloudbuild.googleapis.com

      - name: Build & Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_RUN_SERVICE }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCLOUD_RUN_SERVICE }}             --image gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_RUN_SERVICE }}             --platform managed             --region ${{ secrets.GCLOUD_REGION }}             --allow-unauthenticated             --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }},JWT_SECRET=${{ secrets.JWT_SECRET }},GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
